export const PATHS = {
  REGISTER: 'register',
  REGISTER_PAT: 'registerPat',
  LOGIN: 'login',
  REGISTERDOCTOR: 'registerDoc',
  HOMEDOCTOR: 'homeDoc',
  HOMEPATIENT: 'homePatient',
  MAP: 'map',
  PERFILDOCTOR: 'perfilDoc',
  PERFILPATIENT: 'perfilPat',
  ACTIVITYPAT: 'activityPat',
  DOCINFOINPAT: 'docInfoPat',
  ACTIVITYDOC: 'activityDoc',
  PERSONALDATADOC: 'PersonalDataDoc',
  MODIFYPERSONALDATADOC: 'ModifyPersonalDataDoc',
  PERSONALDATA: 'personalDataPat',
  MODIFYPATDATA: 'modifyDataPat',
  FAMILYMEMBERS: 'familyMembersPat',
  FAMILYMEMBERACTIVITY: 'familyMemberAct',
  HELPPAT: 'helpPat',
  HELPDOC: 'helpDoc',
};
